name: Build ATS-Mini

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install --upgrade pip && pip install platformio esptool requests
      - run: pio run -e ats-mini
      - uses: actions/upload-artifact@v6
        with:
          name: Launcher-ats-mini
          path: .pio/build/ats-mini/firmware.bin
          retention-days: 30
